swagger: "2.0"
info:
  title: "Webhook API"
  version: "1.0.1"
host: "your-domain.com"
schemes:
  - "https"
paths:
  /webhook/your-path:
    post:
      summary: "Trigger webhook with user data"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              chatInput:
                type: "string"
                example: "test"
      responses:
        200:
          description: "Webhook triggered successfully"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                output:
                  type: "string"
                  example: "this is the sample response i found from your db"
        default:
          description: "Error occurred"
      security:
        - apiKey: []
securityDefinitions:
  apiKey:
    type: "apiKey"
    name: "Authorization"
    in: "header"